# Makefile generated by imake - do not edit!

# -------------------------------------------------------------------------
# Makefile generated from "Imake.tmpl" and <Imakefile>
#
# Platform-specific parameters may be set in the appropriate <vendor>.cf
# configuration files.  Site-specific parameters should be set in the file
# site.def.  Full rebuilds are recommended if any parameters are changed.
#

# -------------------------------------------------------------------------
# site-specific configuration parameters that need to come before
# the platform-specific parameters - edit site.def to change

# -------------------------------------------------------------------------
# platform-specific configuration parameters - edit MacroFile to change

# hardware:              i386
# operating system:      Darwin 19.4.0
# operating system path: darwin.19.4.0.i386

# -------------------------------------------------------------------------
# site-specific configuration parameters that go after
# the platform-specific parameters - edit site.def to change

            SHELL = /bin/sh

              TOP = .
      CURRENT_DIR = .
     EXECUTABLESUFFIX =

               AR = ar rcv
              XAR = true
               AS = as
              AWK = awk
               CC = gcc
              CCC = g++
         COMPRESS = bzip2
       UNCOMPRESS = bzip2 -d
      COMPRESSEXT = bz2
              TAR = tar
           TAREXT = tar
          INSTALL = install -c
            STRIP = strip
               LD = ld
               LN = ln -s
             MAKE = make
               MV = mv
               CP = cp

           RANLIB = ranlib
  RANLIBINSTFLAGS =

               RM = rm -rf
             SORT = _POSIX2_VERSION=199209 sort
        WHATISMAN = catman -w

            IMAKE = imake
           DEPEND = /opt/X11/bin/makedepend
        MKDIRHIER = mkdirhier
            MKDIR = mkdirhier

             YACC = yacc
          YACCLIB = -ly
              LEX = flex
           LEXLIB = -lfl

          DOXYGEN = doxygen

     INSTPGMFLAGS = -s
     INSTBINFLAGS = -m 0755
     INSTUIDFLAGS = -m 4755
     INSTLIBFLAGS = -m 0644
     INSTINCFLAGS = -m 0444
     INSTMANFLAGS = -m 0444
     INSTDATFLAGS = -m 0444

             C_STD_INCLUDES =
              C_STD_DEFINES =
         C_EXTRA_LOAD_FLAGS =
          C_EXTRA_LIBRARIES =
           C_OPTIMIZEDFLAGS = -O
         C_UNOPTIMIZEDFLAGS =
               C_DEBUGFLAGS = -O
                  C_OPTIONS =

     CPLUSPLUS_STD_INCLUDES =
      CPLUSPLUS_STD_DEFINES =
 CPLUSPLUS_EXTRA_LOAD_FLAGS =
  CPLUSPLUS_EXTRA_LIBRARIES =
   CPLUSPLUS_OPTIMIZEDFLAGS = -O  -Wno-deprecated
 CPLUSPLUS_UNOPTIMIZEDFLAGS =  -Wno-deprecated
       CPLUSPLUS_DEBUGFLAGS = -O  -Wno-deprecated
          CPLUSPLUS_OPTIONS =

            DISP_LOAD_FLAGS = -L$(X11LIBRARYPATH) -lX11 -lXext
            DISP_INCL_FLAGS = -I$(X11INCLUDEPATH)
             NET_LOAD_FLAGS =

     C_DEFINES_HASSTDNAMESPACEFORSTREAMPOS = -DHASSTDNAMESPACEFORSTREAMPOS=0

     C_DEFINES_USESTANDARDHEADERSWITHOUTEXTENSION = -DUSESTANDARDHEADERSWITHOUTEXTENSION=0

     C_DEFINES_EMITUSINGSTDNAMESPACE = -DEMITUSINGSTDNAMESPACE=0

     C_DEFINES_HASGETHOSTID = -DHASGETHOSTID=1

     C_DEFINES_HASGETHOSTIDPROTOTYPE = -DHASGETHOSTIDPROTOTYPE=1

     C_DEFINES_USEDUMBINFINITYANDNAN = -DUSEDUMBINFINITYANDNAN=1

     C_DEFINES_USEGLIBCTIMEZONE = -DUSEGLIBCTIMEZONE=1

     C_DEFINES_USEXMITSHMEXTENSION = -DUSEXMITSHMEXTENSION=0

            C_ALLINCLUDES = $(C_INCLUDES) $(C_EXTRA_INCLUDES)                             $(C_TOP_INCLUDES) $(C_STD_INCLUDES)

             C_ALLDEFINES = $(C_ALLINCLUDES) $(C_STD_DEFINES)                             $(C_EXTRA_DEFINES) $(C_PROTO_DEFINES)                             $(C_DEFINES)                             $(C_DEFINES_POWINTEGEREXPONENTTYPE)                             $(C_DEFINES_USEGLIBCTIMEZONE)                             $(C_DEFINES_USEDUMBINFINITYANDNAN)                             $(C_DEFINES_HASSTDNAMESPACEFORSTREAMPOS)                             $(C_DEFINES_USESTANDARDHEADERSWITHOUTEXTENSION)                             $(C_DEFINES_EMITUSINGSTDNAMESPACE)                             $(C_DEFINES_HASGETHOSTID)                             $(C_DEFINES_HASGETHOSTIDPROTOTYPE)                             $(C_DEFINES_USEXMITSHMEXTENSION)                             $(C_DEFINES_DEFAULTGUESSEDDATEORDER)                             $(C_DEFINES_BINARYIOFLAGS)

                   CFLAGS = $(C_DEBUGFLAGS) $(C_OPTIONS) $(C_ALLDEFINES)                             $(C_UNOPTIMIZEDFLAGS)

                 C_LDLIBS = $(C_SYS_LIBRARIES) $(C_EXTRA_LIBRARIES)
              C_LDOPTIONS = $(C_DEBUGFLAGS) $(C_OPTIONS) $(C_LOCAL_LDFLAGS)
            C_DEPENDFLAGS =

    CPLUSPLUS_ALLINCLUDES = $(CPLUSPLUS_INCLUDES) $(CPLUSPLUS_EXTRA_INCLUDES)                             $(CPLUSPLUS_TOP_INCLUDES) $(CPLUSPLUS_STD_INCLUDES)

     CPLUSPLUS_ALLDEFINES = $(CPLUSPLUS_ALLINCLUDES) $(CPLUSPLUS_STD_DEFINES)                             $(CPLUSPLUS_EXTRA_DEFINES)                             $(CPLUSPLUS_PROTO_DEFINES) $(CPLUSPLUS_DEFINES)                             $(C_DEFINES_POWINTEGEREXPONENTTYPE)                             $(C_DEFINES_USEGLIBCTIMEZONE)                             $(C_DEFINES_USEDUMBINFINITYANDNAN)                             $(C_DEFINES_HASSTDNAMESPACEFORSTREAMPOS)                             $(C_DEFINES_USESTANDARDHEADERSWITHOUTEXTENSION)                             $(C_DEFINES_EMITUSINGSTDNAMESPACE)                             $(C_DEFINES_HASGETHOSTID)                             $(C_DEFINES_HASGETHOSTIDPROTOTYPE)                             $(C_DEFINES_USEXMITSHMEXTENSION)                             $(C_DEFINES_DEFAULTGUESSEDDATEORDER)                             $(C_DEFINES_BINARYIOFLAGS)

          CPLUSPLUS_FLAGS = $(CPLUSPLUS_DEBUGFLAGS) $(CPLUSPLUS_OPTIONS)                             $(CPLUSPLUS_UNOPTIMIZEDFLAGS)                             $(CPLUSPLUS_ALLDEFINES)

         CPLUSPLUS_LDLIBS = $(CPLUSPLUS_SYS_LIBRARIES)                             $(CPLUSPLUS_EXTRA_LIBRARIES)

      CPLUSPLUS_LDOPTIONS = $(CPLUSPLUS_DEBUGFLAGS) $(CPLUSPLUS_OPTIONS)                             $(CPLUSPLUS_LOCAL_LDFLAGS)

    CPLUSPLUS_DEPENDFLAGS =

                   RM_CMD = $(RM) *.CKP *.ln *.BAK *.bak *.o core errs ,* *~ *.a .emacs_* tags TAGS make.log MakeOut a.out .sb ii_files Templates.DB mon.out gmon.out

            IMAKE_DEFINES =
                IMAKE_CMD = $(IMAKE) 			-I$(NEWTOP)$(PRIVCONFIGDIR) 			$(IMAKE_DEFINES)

           X11LIBRARYPATH = /opt/X11/lib
           X11INCLUDEPATH = /opt/X11/include

.SUFFIXES:	.c
.c.o:	; $(CC) -c $(CFLAGS) $*.c

.SUFFIXES:	.cc
.cc.o:	; $(CCC) -c $(CPLUSPLUS_FLAGS) $*.cc

                  PLATFORMNAME = darwin.19.4.0.i386

             PROJECTINCLUDEDIR = $(TOP)/libsrc/include
              PROJECTLIBSRCDIR = $(TOP)/libsrc/src
                 PROJECTLIBDIR = $(TOP)/libsrc/lib
          PROJECTLIBSUPPORTDIR = $(TOP)/libsrc/support
         PROJECTLIBSTANDARDDIR = $(TOP)/libsrc/standard

             PROJECTSUPPORTDIR = $(TOP)/support

         PROJECTGENERICLIBNAME = gener
          PROJECTDCTOOLLIBNAME = dctl
          PROJECTDCDISPLIBNAME = ddply
         PROJECTOURDISPLIBNAME = odply
        PROJECTDCONVERTLIBNAME = dconv
          PROJECTLOCALELIBNAME = dlcl

             PROJECTGENERICLIB = -l$(PROJECTGENERICLIBNAME)
            PROJECTDCONVERTLIB = -l$(PROJECTDCONVERTLIBNAME)
              PROJECTDCTOOLLIB = -l$(PROJECTDCTOOLLIBNAME)
              PROJECTDCDISPLIB = -l$(PROJECTDCDISPLIBNAME)
             PROJECTOURDISPLIB = -l$(PROJECTOURDISPLIBNAME)
              PROJECTLOCALELIB = -l$(PROJECTLOCALELIBNAME)

            PROJECTACRNEMALIBS = $(PROJECTDCTOOLLIB)   $(PROJECTLOCALELIB)  $(PROJECTGENERICLIB)
           PROJECTDCONVERTLIBS = $(PROJECTDCONVERTLIB) $(PROJECTDCTOOLLIB)  $(PROJECTLOCALELIB)  $(PROJECTGENERICLIB)
             PROJECTDCFILELIBS = $(PROJECTDCTOOLLIB)   $(PROJECTLOCALELIB)  $(PROJECTGENERICLIB)
             PROJECTDCDISPLIBS = $(PROJECTDCDISPLIB)   $(PROJECTOURDISPLIB) $(PROJECTDCTOOLLIB)  $(PROJECTLOCALELIB) $(PROJECTGENERICLIB) -L$(X11LIBRARYPATH) -lX11 -lXext
               PROJECTMISCLIBS = $(PROJECTLOCALELIB)   $(PROJECTGENERICLIB)
                PROJECTALLLIBS = $(PROJECTDCONVERTLIB) $(PROJECTDCDISPLIB)  $(PROJECTOURDISPLIB) $(PROJECTDCTOOLLIB) $(PROJECTLOCALELIB) $(PROJECTGENERICLIB) -L$(X11LIBRARYPATH) -lX11 -lXext

          PROJECTGENERICDEPLIB = $(PROJECTLIBDIR)/lib$(PROJECTGENERICLIBNAME).a
         PROJECTDCONVERTDEPLIB = $(PROJECTLIBDIR)/lib$(PROJECTDCONVERTLIBNAME).a
           PROJECTDCTOOLDEPLIB = $(PROJECTLIBDIR)/lib$(PROJECTDCTOOLLIBNAME).a
           PROJECTDCDISPDEPLIB = $(PROJECTLIBDIR)/lib$(PROJECTDCDISPLIBNAME).a
          PROJECTOURDISPDEPLIB = $(PROJECTLIBDIR)/lib$(PROJECTOURDISPLIBNAME).a
           PROJECTLOCALEDEPLIB = $(PROJECTLIBDIR)/lib$(PROJECTLOCALELIBNAME).a

         PROJECTACRNEMADEPLIBS = $(PROJECTDCTOOLDEPLIB)   $(PROJECTLOCALEDEPLIB)  $(PROJECTGENERICDEPLIB)
        PROJECTDCONVERTDEPLIBS = $(PROJECTDCONVERTDEPLIB) $(PROJECTDCTOOLDEPLIB)  $(PROJECTLOCALEDEPLIB)  $(PROJECTGENERICDEPLIB)
          PROJECTDCFILEDEPLIBS = $(PROJECTDCTOOLDEPLIB)   $(PROJECTLOCALEDEPLIB)  $(PROJECTGENERICDEPLIB)
          PROJECTDCDISPDEPLIBS = $(PROJECTDCDISPDEPLIB)   $(PROJECTOURDISPDEPLIB) $(PROJECTDCTOOLDEPLIB)  $(PROJECTLOCALEDEPLIB) $(PROJECTGENERICDEPLIB)
            PROJECTMISCDEPLIBS = $(PROJECTLOCALEDEPLIB)   $(PROJECTGENERICDEPLIB)
             PROJECTALLDEPLIBS = $(PROJECTDCONVERTDEPLIB) $(PROJECTDCDISPDEPLIB)  $(PROJECTOURDISPDEPLIB) $(PROJECTDCTOOLDEPLIB) $(PROJECTLOCALEDEPLIB) $(PROJECTGENERICDEPLIB)

  PROJECTGENERICINCLUDEDIRNAME = generic
   PROJECTLOCALEINCLUDEDIRNAME = locale
   PROJECTDCTOOLINCLUDEDIRNAME = dctool
   PROJECTDCDISPINCLUDEDIRNAME = dcdisp
  PROJECTOURDISPINCLUDEDIRNAME = ourdisp
 PROJECTPIXELDATINCLUDEDIRNAME = pixeldat
 PROJECTDCONVERTINCLUDEDIRNAME = dconvert

 PROJECTLIBGENERICEXTRAINCLUDES = -I$(PROJECTINCLUDEDIR)/$(PROJECTGENERICINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTLOCALEINCLUDEDIRNAME)

 PROJECTLIBOURDISPEXTRAINCLUDES = -I$(PROJECTINCLUDEDIR)/$(PROJECTGENERICINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTLOCALEINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTOURDISPINCLUDEDIRNAME)                                   -I$(X11INCLUDEPATH)

PROJECTLIBDCONVERTEXTRAINCLUDES = -I$(PROJECTINCLUDEDIR)/$(PROJECTGENERICINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTLOCALEINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTDCTOOLINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTPIXELDATINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTDCONVERTINCLUDEDIRNAME)

  PROJECTLIBDCDISPEXTRAINCLUDES = -I$(PROJECTINCLUDEDIR)/$(PROJECTGENERICINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTLOCALEINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTDCDISPINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTDCTOOLINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTOURDISPINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTPIXELDATINCLUDEDIRNAME)                                   -I$(X11INCLUDEPATH)

  PROJECTLIBDCTOOLEXTRAINCLUDES = -I$(PROJECTINCLUDEDIR)/$(PROJECTGENERICINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTLOCALEINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTDCTOOLINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTPIXELDATINCLUDEDIRNAME)

  PROJECTLIBLOCALEEXTRAINCLUDES = -I$(PROJECTINCLUDEDIR)/$(PROJECTGENERICINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTLOCALEINCLUDEDIRNAME)

 PROJECTAPPACRNEMAEXTRAINCLUDES = -I$(PROJECTINCLUDEDIR)/$(PROJECTGENERICINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTLOCALEINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTDCTOOLINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTPIXELDATINCLUDEDIRNAME)

  PROJECTAPPDCDISPEXTRAINCLUDES = -I$(PROJECTINCLUDEDIR)/$(PROJECTGENERICINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTLOCALEINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTDCDISPINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTDCTOOLINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTOURDISPINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTPIXELDATINCLUDEDIRNAME)                                   -I$(X11INCLUDEPATH)

  PROJECTAPPDCFILEEXTRAINCLUDES = -I$(PROJECTINCLUDEDIR)/$(PROJECTGENERICINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTLOCALEINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTDCTOOLINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTPIXELDATINCLUDEDIRNAME)

PROJECTAPPDCONVERTEXTRAINCLUDES = -I$(PROJECTINCLUDEDIR)/$(PROJECTGENERICINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTLOCALEINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTDCTOOLINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTPIXELDATINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTDCONVERTINCLUDEDIRNAME)

    PROJECTAPPMISCEXTRAINCLUDES = -I$(PROJECTINCLUDEDIR)/$(PROJECTGENERICINCLUDEDIRNAME)                                   -I$(PROJECTINCLUDEDIR)/$(PROJECTLOCALEINCLUDEDIRNAME)

        CPLUSPLUS_LOCAL_LDFLAGS = -L$(PROJECTLIBDIR)

                      C_DEFINES = -DDEFAULTUIDROOT=\"0.0.0.0\" -DDEFAULTINSTANCECREATORUID=\"0.0.0.0\" -DDEFAULTIMPLEMENTATIONCLASSUID=\"0.0.0.0\" -DDEFAULTIMPLEMENTATIONVERSIONNAME=\"NOTSPECIFIED\" -DDEFAULTSOURCEAPPLICATIONENTITYTITLE=\"NOTSPECIFIED\"
              CPLUSPLUS_DEFINES = -DDEFAULTUIDROOT=\"0.0.0.0\" -DDEFAULTINSTANCECREATORUID=\"0.0.0.0\" -DDEFAULTIMPLEMENTATIONCLASSUID=\"0.0.0.0\" -DDEFAULTIMPLEMENTATIONVERSIONNAME=\"NOTSPECIFIED\" -DDEFAULTSOURCEAPPLICATIONENTITYTITLE=\"NOTSPECIFIED\"

.SUFFIXES:	.xbm .cbm
.xbm.cbm:	;$(PROJECTSUPPORTDIR)/xbmtocbm $< $@

# -------------------------------------------------------------------------

   PRIVCONFIGDIR = $(TOP)/config

          PATHSEP = /
    INSTALLBINDIR = /usr/local/bin
    INSTALLINCDIR = /usr/local/include
    INSTALLLIBDIR = /usr/local/lib
    INSTALLMANDIR = /usr/local/man

# -------------------------------------------------------------------------
# Imake rules for building libraries, programs, scripts, and data files
# rules:  $XConsortium: Imake.rules,v 1.123 91/09/16 20:12:16 rws Exp $

# -------------------------------------------------------------------------
# start of Imakefile

SUBDIRS        = appsrc config libsrc support
ALLSUBDIRS     = libsrc appsrc support
DEPENDSUBDIRS  = libsrc appsrc support
SBSOURCEDIRS   = libsrc appsrc support
SBDIR          = .sb
INSTALLDIRS    = bin include lib man

ARCHIVENAME        = dicom3tools
ARCHIVEFILES       = $(SUBDIRS) BUGS CHANGES Configure COPYRIGHT Doxyfile Imakefile INSTALL Makefile NotAMakefile README TODO VERSION WARNINGS

ARCHIVEIMAGESNAME  = dicom3tools_images
ARCHIVEIMAGESFILES  = images

ARCHIVETESTNAME  = dicom3tools_test
ARCHIVETESTFILES  = test

ARCHIVEMANNAME  = dicom3tools_man
ARCHIVEMANFILES  = man

ARCHIVEWINEXENAME = dicom3tools_winexe
ARCHIVEWINEXEFILES = 	appsrc/acrnema/andump.exe 	/usr/bin/cygwin1.dll 	/usr/bin/cyggcc_s-1.dll 	/usr/bin/cygstdc++-6.dll 	appsrc/dcfile/dcdump.exe 	appsrc/dcfile/dcentvfy.exe 	appsrc/dcfile/dcfile.exe 	appsrc/dcfile/dchist.exe 	appsrc/dcfile/dciodvfy.exe 	appsrc/dcfile/dckey.exe 	appsrc/dcfile/dcsrdump.exe 	appsrc/dcfile/dcstats.exe 	appsrc/dcfile/dctable.exe 	appsrc/dcfile/dcsort.exe 	appsrc/dcfile/dcdirdmp.exe 	appsrc/dcfile/dctoraw.exe 	appsrc/dcfile/dccmp.script 	appsrc/dcfile/dcdiff.script

ARCHIVEMACEXENAME = dicom3tools_macexe
ARCHIVEMACEXEFILES = 	appsrc/acrnema/andump 	appsrc/dcfile/dcdump 	appsrc/dcfile/dcentvfy 	appsrc/dcfile/dcfile 	appsrc/dcfile/dchist 	appsrc/dcfile/dciodvfy 	appsrc/dcfile/dckey 	appsrc/dcfile/dcsrdump 	appsrc/dcfile/dcstats 	appsrc/dcfile/dctable 	appsrc/dcfile/dcsort 	appsrc/dcfile/dcdirdmp 	appsrc/dcfile/dctoraw 	appsrc/dcfile/dccmp.script 	appsrc/dcfile/dcdiff.script

LINKTOIMAGEDIR = ../dctool.support/images
LINKTOTESTDIR = ../dctool.support/test

all::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(ALLSUBDIRS) ;\
	do \
		(cd $$i ; echo "making" all "in $(CURRENT_DIR)/$$i..."; \
			$(MAKE) $(MFLAGS) 'C_DEBUGFLAGS=$(C_DEBUGFLAGS)' 'CPLUSPLUS_DEBUGFLAGS=$(CPLUSPLUS_DEBUGFLAGS)' all); \
	done

depend::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(DEPENDSUBDIRS) ;\
	do \
		(cd $$i ; echo "depending" "in $(CURRENT_DIR)/$$i..."; \
			$(MAKE) $(MFLAGS)  depend); \
	done

World:
	$(MAKE) $(MFLAGS) Makefile
	$(MAKE) $(MFLAGS) Makefiles
	$(MAKE) $(MFLAGS) clean
	$(MAKE) $(MFLAGS) depend
	$(MAKE) $(MFLAGS) setplatform
	$(MAKE) $(MFLAGS)

World.unclean:
	$(MAKE) $(MFLAGS) Makefile
	$(MAKE) $(MFLAGS) Makefiles
	$(MAKE) $(MFLAGS) depend
	$(MAKE) $(MFLAGS) setplatform
	$(MAKE) $(MFLAGS)

library::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in libsrc ;\
	do \
		(cd $$i ; echo  "in $(CURRENT_DIR)/$$i..."; \
			$(MAKE) $(MFLAGS)  all); \
	done

install.whatis::
	$(WHATISMAN) -M $(INSTALLMANDIR)

sb:	$(SBSOURCEDIRS)
	support/linksb $(SBDIR) $(SBSOURCEDIRS)

update.copyright:
	support/updatecopyright

setversion:
	support/setversion

setplatform:
	support/setplatform

archive:	setversion clean clean.makefiles clean.config clean.docs archive.unclean

archive.unclean:
	$(CP) NotAMakefile Makefile; 	version=""; 	if [ -f VERSION ]; 		then version="_"`cat VERSION`; fi; 	link=$(ARCHIVENAME)$$version; 	ln -s . $$link; 	archive=$(ARCHIVENAME)$$version.$(TAREXT).$(COMPRESSEXT); 	sedstring="s/^[.]/$$link/"; 	export COPY_EXTENDED_ATTRIBUTES_DISABLE=true; export COPYFILE_DISABLE=true; 	echo 'CVS' >Exclude; echo '.DS_Store' >>Exclude; 	if [ -f $$archive ]; then $(MV) $$archive $$archive.old; fi; 	$(TAR) -X Exclude -cvf - `for i in $(ARCHIVEFILES); do echo $$link/$$i; done` 		| $(COMPRESS) > $$archive; 	$(RM) $$link Exclude

archive.images:
	version=""; 	if [ -f VERSION ]; 		then version="_"`cat VERSION`; fi; 	link=$(ARCHIVEIMAGESNAME)$$version; 	ln -s . $$link; 	archive=$(ARCHIVEIMAGESNAME)$$version.$(TAREXT).$(COMPRESSEXT); 	sedstring="s/^[.]/$$link/"; 	export COPY_EXTENDED_ATTRIBUTES_DISABLE=true; export COPYFILE_DISABLE=true; 	find . -path '*/CVS/*' | sed -e "$$sedstring" >Exclude; 	if [ -f $$archive ]; then $(MV) $$archive $$archive.old; fi; 	$(TAR) -X Exclude -cvh -f - `for i in $(ARCHIVEIMAGESFILES); do echo $$link/$$i; done` 		| $(COMPRESS) > $$archive; 	$(RM) $$link Exclude

archive.test:
	version=""; 	if [ -f VERSION ]; 		then version="_"`cat VERSION`; fi; 	link=$(ARCHIVETESTNAME)$$version; 	ln -s . $$link; 	archive=$(ARCHIVETESTNAME)$$version.$(TAREXT).$(COMPRESSEXT); 	sedstring="s/^[.]/$$link/"; 	export COPY_EXTENDED_ATTRIBUTES_DISABLE=true; export COPYFILE_DISABLE=true; 	find . -path '*/CVS/*' | sed -e "$$sedstring" >Exclude; 	if [ -f $$archive ]; then $(MV) $$archive $$archive.old; fi; 	$(TAR) -X Exclude -cvh -f - `for i in $(ARCHIVETESTFILES); do echo $$link/$$i; done` 		| $(COMPRESS) > $$archive; 	$(RM) $$link Exclude

archive.man: install.man
	version=""; 	if [ -f VERSION ]; 		then version="_"`cat VERSION`; fi; 	link=$(ARCHIVEMANNAME)$$version; 	ln -s . $$link; 	archive=$(ARCHIVEMANNAME)$$version.$(TAREXT).$(COMPRESSEXT); 	sedstring="s/^[.]/$$link/"; 	export COPY_EXTENDED_ATTRIBUTES_DISABLE=true; export COPYFILE_DISABLE=true; 	find . -path '*/CVS/*' | sed -e "$$sedstring" >Exclude; 	if [ -f $$archive ]; then $(MV) $$archive $$archive.old; fi; 	$(TAR) -X Exclude -cvf - `for i in $(ARCHIVEMANFILES); do echo $$link/$$i; done` 		| $(COMPRESS) > $$archive; 	$(RM) $$link Exclude

archive.winexe:
	version=""; 	if [ -f VERSION ]; 		then version="_"`cat VERSION`; fi; 	link=$(ARCHIVEWINEXENAME)$$version; 	$(RM) $$link; 	mkdir -p $$link; 	cp $(ARCHIVEWINEXEFILES) $$link; 	archive=$(ARCHIVEWINEXENAME)$$version.zip; 	$(RM) $$archive; 	(cd $$link; for i in *.exe; do touch $$i.local; done); 	(cd $$link; zip ../$$archive *.script *.exe *.dll *.exe.local); 	$(RM) $$link

archive.macexe:
	#version="_"`uname -p`"_"`uname -s`"_"`uname -r`
	version=""; 	if [ -f VERSION ]; 		then version=$$version"_"`cat VERSION`; fi; 	link=$(ARCHIVEMACEXENAME)$$version; 	$(RM) $$link; 	mkdir -p $$link; 	cp $(ARCHIVEMACEXEFILES) $$link; 	archive=$(ARCHIVEMACEXENAME)$$version.zip; 	$(RM) $$archive; 	(cd $$link; zip ../$$archive dc* an*); 	$(RM) $$link

clean.installed:
	$(RM) $(INSTALLDIRS)

clean.sb:
	$(RM) $(SBDIR)

clean.makefiles:
	$(RM) `find . -name 'Makefile*' -print`

clean.config:
	$(RM) config/generic.cf

clean.docs:
	$(RM) docs

clean.dist: clean clean.makefiles clean.config clean.installed clean.sb clean.docs
	$(RM) Exclude

find.pre:
	support/findpre

clean.pre:
	$(RM) `support/findpre`

install.minimal:
	$(INSTALL) $(INSTPGMFLAGS) $(INSTBINFLAGS) 		appsrc/acrnema/andump /usr/local/bin

	$(INSTALL) $(INSTPGMFLAGS) $(INSTBINFLAGS) 		appsrc/dcdisp/dcdisp /usr/local/bin

	$(INSTALL) $(INSTPGMFLAGS) $(INSTBINFLAGS) 		appsrc/dcfile/dcdump /usr/local/bin

	$(INSTALL) $(INSTPGMFLAGS) $(INSTBINFLAGS) 		appsrc/dcfile/dciodvfy /usr/local/bin

	$(INSTALL) $(INSTPGMFLAGS) $(INSTBINFLAGS) 		appsrc/dcfile/dcdict /usr/local/bin

links:
	ln -s $(LINKTOIMAGEDIR)
	ln -s $(LINKTOTESTDIR)

docs:	. clean.docs
	$(MKDIR) docs
	$(DOXYGEN) Doxyfile

# -------------------------------------------------------------------------
# common rules for all Makefiles - do not edit

emptyrule::

clean::
	$(RM_CMD) "#"*

Makefile::
	-@if [ -f Makefile ]; then set -x; \
		$(RM) Makefile.bak; $(MV) Makefile Makefile.bak; \
	else exit 0; fi
	$(IMAKE_CMD) -DTOPDIR=$(TOP) -DCURDIR=$(CURRENT_DIR)       -DTmpPath=/Users/afshin/Documents/softwares/dicom3tools/temp   -DSystemIncludeOption=-I

# -------------------------------------------------------------------------
# rules for building in SUBDIRS - do not edit

test::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo "testing" "in $(CURRENT_DIR)/$$i..."; \
			$(MAKE) $(MFLAGS) DESTDIR='$(DESTDIR)' test); \
	done

test.create::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo "creating tests" "in $(CURRENT_DIR)/$$i..."; \
			$(MAKE) $(MFLAGS) DESTDIR='$(DESTDIR)' test.create); \
	done

install::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo "installing" "in $(CURRENT_DIR)/$$i..."; \
			$(MAKE) $(MFLAGS) DESTDIR='$(DESTDIR)' install); \
	done

install.man::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo "installing man pages" "in $(CURRENT_DIR)/$$i..."; \
			$(MAKE) $(MFLAGS) DESTDIR='$(DESTDIR)' install.man); \
	done

clean::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo "cleaning" "in $(CURRENT_DIR)/$$i..."; \
			$(MAKE) $(MFLAGS) RM_CMD='$(RM_CMD)' clean); \
	done

Makefiles::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		echo "making Makefiles in $(CURRENT_DIR)/$$i..."; \
		case "$$i" in \
		./?*/?*/?*/?*) newtop=../../../../ sub=subsubsubsub;; \
		./?*/?*/?*) newtop=../../../ sub=subsubsub;; \
		./?*/?*)    newtop=../../ sub=subsub;; \
		./?*)       newtop=../ sub=sub;; \
		*/?*/?*/?*)    newtop=../../../../ sub=subsubsubsub;; \
		*/?*/?*)    newtop=../../../ sub=subsubsub;; \
		*/?*)       newtop=../../ sub=subsub;; \
		*)	    newtop=../ sub=sub;; \
		esac; \
		case "$(TOP)" in \
		/?*) newtop=  upprefix=  ;; \
		*) upprefix=../ ;; \
		esac; \
		$(MAKE) $${sub}dirMakefiles UPPREFIX=$$upprefix NEWTOP=$$newtop \
		MAKEFILE_SUBDIR=$$i NEW_CURRENT_DIR=$(CURRENT_DIR)/$$i;\
	done

subdirMakefiles:
	$(RM) $(MAKEFILE_SUBDIR)/Makefile.bak
	-@if [ -f $(MAKEFILE_SUBDIR)/Makefile ]; then set -x; \
	$(MV) $(MAKEFILE_SUBDIR)/Makefile $(MAKEFILE_SUBDIR)/Makefile.bak; \
	else exit 0; fi
	cd $(MAKEFILE_SUBDIR); $(IMAKE_CMD) -DTOPDIR=$(UPPREFIX)$(TOP) -DCURDIR=$(NEW_CURRENT_DIR)       -DTmpPath=/Users/afshin/Documents/softwares/dicom3tools/temp   -DSystemIncludeOption=-I; \
	$(MAKE) $(MFLAGS) Makefiles

subsubdirMakefiles:
	$(RM) $(MAKEFILE_SUBDIR)/Makefile.bak
	-@if [ -f $(MAKEFILE_SUBDIR)/Makefile ]; then set -x; \
	$(MV) $(MAKEFILE_SUBDIR)/Makefile $(MAKEFILE_SUBDIR)/Makefile.bak; \
	else exit 0; fi
	cd $(MAKEFILE_SUBDIR); $(IMAKE_CMD) -DTOPDIR=$(UPPREFIX)$(UPPREFIX)$(TOP) -DCURDIR=$(NEW_CURRENT_DIR)       -DTmpPath=/Users/afshin/Documents/softwares/dicom3tools/temp   -DSystemIncludeOption=-I; \
	$(MAKE) $(MFLAGS) Makefiles

subsubsubdirMakefiles:
	$(RM) $(MAKEFILE_SUBDIR)/Makefile.bak
	-@if [ -f $(MAKEFILE_SUBDIR)/Makefile ]; then set -x; \
	$(MV) $(MAKEFILE_SUBDIR)/Makefile $(MAKEFILE_SUBDIR)/Makefile.bak; \
	else exit 0; fi
	cd $(MAKEFILE_SUBDIR); $(IMAKE_CMD) -DTOPDIR=$(UPPREFIX)$(UPPREFIX)$(UPPREFIX)$(TOP) -DCURDIR=$(NEW_CURRENT_DIR)       -DTmpPath=/Users/afshin/Documents/softwares/dicom3tools/temp   -DSystemIncludeOption=-I; \
	$(MAKE) $(MFLAGS) Makefiles

subsubsubsubdirMakefiles:
	$(RM) $(MAKEFILE_SUBDIR)/Makefile.bak
	-@if [ -f $(MAKEFILE_SUBDIR)/Makefile ]; then set -x; \
	$(MV) $(MAKEFILE_SUBDIR)/Makefile $(MAKEFILE_SUBDIR)/Makefile.bak; \
	else exit 0; fi
	cd $(MAKEFILE_SUBDIR); $(IMAKE_CMD) -DTOPDIR=$(UPPREFIX)$(UPPREFIX)$(UPPREFIX)$(UPPREFIX)$(TOP) -DCURDIR=$(NEW_CURRENT_DIR)       -DTmpPath=/Users/afshin/Documents/softwares/dicom3tools/temp   -DSystemIncludeOption=-I; \
	$(MAKE) $(MFLAGS) Makefiles

includes::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo including "in $(CURRENT_DIR)/$$i..."; \
			$(MAKE) $(MFLAGS)  includes); \
	done

# -------------------------------------------------------------------------
# dependencies generated by makedepend

