// Automatically generated - EDITS WILL BE LOST

// Generated by support/setplatform

#include "platform.h"

const char* dicom3tools_platform_string = "Darwin beat.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64";
